# Generated by Django 5.0.14 on 2025-07-09 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productVariant', to='shop.product'),
        ),
    ]
