# Generated by Django 5.0.14 on 2025-07-09 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(0, '1 Star'), (1, '2 Stars'), (2, '3 Stars'), (3, '4 Stars'), (4, '5 Stars')], default=4),
        ),
    ]
