# Generated by Django 5.0.14 on 2025-07-11 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_productvariant_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='subject',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
