# Generated by Django 5.0.14 on 2025-07-20 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_backinstock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backinstock',
            old_name='product',
            new_name='variant',
        ),
    ]
