# Generated by Django 5.0.14 on 2025-07-21 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_rename_product_backinstock_variant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PromoCode',
        ),
    ]
